gorilla/sessions

- README.md
- doc.go
- sessions.go
Straight from `doc.go` in this case—plus a minor change to docs around `Save`.
> Fleshed out README with example from doc.go + build/godoc badges.

- doc.go
Also removed calls to fmt.Fprintf in AddFlash example.  If a user
follows the old example then the session won't be stored.
See: https://github.com/gorilla/sessions/issues/39
> Added note about calling save before writing to response.

- store.go
Addresses https://github.com/gorilla/sessions/issues/48
Specifically:
- This is easy enough to set on store creation
- However, the current approach to changing the `MaxAge` for a store is by setting the struct value
- We now provide methods on each store to set the `MaxAge` after store creation and on all underlying codecs.
> Provide method to set MaxAge on underlying cookies.

- README.md
- Removed unmaintained AppEngine store.
> Added goappenginesessioncascade to list of compatible stores.

- README.md
a new store implementation is published, and wish to add the link to ReadME
https://github.com/EnumApps/clustersqlstore
p.s. the store passed unit test
> [docs] Add Store Implementations Project Link - MySQL Cluster

- README.md
This updates the README to add a `sessions.Store` implementation based on https://github.com/cznic/ql database
> Add link to qlstore

- README.md
The current README stops short at a colon where it looks like it should have a code example.
I copied the example in the same section from `doc.go`.
> Add missing ClearHandler example to README

- README.md
Adds a link to memstore, an in-memory implementation of `sessions.Store` for use in unit tests
> Add link to memstore implementation

- sessions.go
- sessions_test.go
> Prevent panic in NewSession function

- options.go
- options_go111.go
- sessions.go
Addresses #164 
Adds support for the [`SameSite`](https://golang.org/pkg/net/http/#SameSite) attribute introduced in Go 1.11 - a new cookie attribute introduced to further prevent CSRF attacks: https://blog.mozilla.org/security/2018/04/24/same-site-cookies-in-firefox-60/
> Adds support for SameSite cookie attribute

- cookie.go
- cookie_go111.go
- cookie_go111_test.go
- cookie_test.go
- sessions.go
Set the returned http.Cookie's SameSite field to the value of the
SameSite field in the Options struct passed into NewCookie.  This
fixes an oversight made in PR #165 which was made to address issue
Add a newCookieFromOptions function which takes a name, value and
Options struct and returns an http.Cookie.  There are two
newCookieFromOptions implementations, one for Go 1.11 and later which
sets SameSite and one for earlier Go versions which does not.
Add new tests TestNewCookieFromOptions and
TestNewCookieFromOptionsSameSite which ensure that the values passed
to newCookieFromOptions are properly set in the returned cookie.  The
test TestNewCookieFromOptionsSameSite only runs if running Go 1.11 and
later.
> Set http.Cookie's SameSite field in NewCookie for Go 1.11 or later

- README.md
`os.Getenv` will return a string, but `NewCookieStore` takes bytes as the argument:
https://github.com/gorilla/sessions/blob/68d1edeb366b66bdd5d714e32d7a065f74b03b9b/store.go#L50
> README: convert key to bytes before passing to NewCookieStore

- .travis.yml
- README.md
- doc.go
- sessions.go
- sessions_test.go
If gorilla/sessions is used together with other solutions including gorilla/mux, then there is a big chance of memory leaks, because the request may change during it's lifetime due to shallow copying of the request when the request context is changing. Once the request is copied, and that copy is used instead, then the request can no longer be found as key in the global context store managed by gorilla/context. This way the expired contexts are remaining in memory forever.
> - use golang context pkg instead of gorilla/context to fix memory leaks

- sessions_test.go
DefaultRemoteAddr seems to not be used (any longer?).
> Removed unused global var

- README.md
- doc.go
This is because I copied the sample and failed to notice there was a return, which for me was failing, and lost a bunch of time to troubleshooting. (Note: I actually copied the samples from here - https://www.gorillatoolkit.org/pkg/sessions - but don't know how to update that page.)
Fixes #
**Summary of Changes**
1. Added _ = 'cos even though the error is ignored this shows one exists
2. 
3.
> PS: Make sure your PR includes/updates tests! If you need help with this part, just ask!
> Added _ = to indicate there is a return from Save

- README.md
I wrote a `Store` implementation backed by Cloud Firestore: https://github.com/GoogleCloudPlatform/firestore-gorilla-sessions.
> README.md: link Cloud Firestore implementation

- README.md
**Added Redis store implementation**
1. Redis store implementation with [go-redis](https://github.com/go-redis/redis) as Redis client. This enables use Redis on single mode, Sentinel and Cluster.
> Add Redis store implementation

- doc.go
Fixes the creation of CookieStore in doc.go
**Summary of Changes**
1.  `sessions.NewCookieStore` method requires a slice of bytes but a string was provided in doc.go file.
> fix CookieStore creation in doc.go

- store.go
**Summary of Changes**
1. Created a base32 encoder with no padding to encode random key
> refactor: use base32 encoder with no padding

- cookie.go
- cookie_go111.go
- cookie_go111_test.go
- options.go
- options_go111.go
Summary of Changes
The CI step that lints the package using latest go version (1.17) fails due to the introduction of new `//go:build ` directives.
This adds them so gofmt doesn't report any differences.
> Fix linting errors for go1.17

- go.mod
- go.sum
- vendor/github.com/gorilla/securecookie/.editorconfig
- vendor/github.com/gorilla/securecookie/.gitignore
- vendor/github.com/gorilla/securecookie/LICENSE
- vendor/github.com/gorilla/securecookie/Makefile
- vendor/github.com/gorilla/securecookie/README.md
- vendor/github.com/gorilla/securecookie/doc.go
- vendor/github.com/gorilla/securecookie/securecookie.go
- vendor/modules.txt
- Related Issue #
- Closes #
have not been included_
> bump deps and add vendor dir

- store.go
```
PASS
coverage: 78.1% of statements
ok  	github.com/gorilla/sessions	1.155s	coverage: 78.1% of statements
```
> Fix path traversal

- cookie.go
- cookie_go111.go
- cookie_test.go
- options.go
- options_go111.go
- vendor/github.com/gorilla/securecookie/README.md
The PR contains the change to add Partitioned attribute in the cookies. As chrome will be deprecating support for 3rd Party cookies, we need to add support for CHIPS to make cookies partitioned to the website.
- Related Issue #
- Closes #272
have not been included_
> #272: feat: Add support for paritioned attribute in cookies as per chrome 3rd party cookie phaseout

- .gitignore
- cookie_go111_test.go
- sessions_test.go
- store.go
This PR sets the SameSite cookie attribute to Lax in the Set-Cookie header. The SameSite=Lax value provides a reasonable balance between security and usability for websites.
Reference: 
https://owasp.org/www-community/SameSite
- Related Issue # https://github.com/gorilla/sessions/issues/256
- Closes # https://github.com/gorilla/sessions/issues/256
have not been included_
Fixes: https://github.com/gorilla/sessions/issues/256
> fix no default samesite

- README.md
Fix "more examples" link not taking you to where more examples are at
- Closes #246
> Fix gorillatoolkit link in README.md
